# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies without running prepare scripts
RUN npm install --ignore-scripts

# Copy the rest of the repository
COPY . .

# Build the project using TypeScript (tsconfig.json is now available)
RUN npm run build

# Expose any necessary ports (if applicable)
# EXPOSE 3000

# Set the entrypoint command to run the MCP server
CMD ["node", "build/index.js"]
